name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: wanna_go_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
    
    env:
      RAILS_ENV: test
      NODE_VERSION: 18.18.0
      DATABASE_URL: "postgres://rails:password@localhost:5432/wanna_go_test"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
      
      - name: Yarn Install
        run: yarn install
      
      - name: Build CSS
        run: yarn build:css
      
      - name: Database Setup
        run: bundle exec rails db:create db:schema:load
      
      - name: Rubocop
        run: bundle exec rubocop
      
      - name: RSpec
        run: bundle exec rspec

  deploy:
    needs: test
    if: ${{ needs.test.result == 'success' && github.ref == 'refs/heads/production' }}
    runs-on: ubuntu-latest

    env:
      deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy To Render
        run: curl "$deploy_url"
